CREATE DATABASE IF NOT EXISTS thermo;

USE thermo;

CREATE TABLE IF NOT EXISTS temps ( 
	measureId INT NOT NULL AUTO_INCREMENT ,
	temp DOUBLE NOT NULL ,
	hum DOUBLE NOT NULL ,
	date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
	thermoId INT(10) NULL DEFAULT NULL ,
	PRIMARY KEY (measureId)
	) ENGINE = InnoDB DEFAULT CHARSET = utf8;